### ISSUE TITLE
encode bytes32 error

### ISSUE THREAD

**Issue by roynalnaruto** [exthereum/abi#31]
Below is the function signature in solidity:
```
get(bytes32)
```

I tried the following:
```
ABI.TypeEncoder.encode_raw([{"63cb2f697029ee491b58939796e9013087104b816ce0f51e731e9b03cc50c3b9"}], [{:tuple, [bytes: 32]}])
```
to which I get the following error:
```
** (RuntimeError) size mismatch for bytes32: "63cb2f697029ee491b58939796e9013087104b816ce0f51e731e9b03cc50c3b9"
    lib/abi/type_encoder.ex:178: ABI.TypeEncoder.encode_type/2
```

This is because here: https://github.com/exthereum/abi/blob/master/lib/abi/type_encoder.ex#L173 , the size required will be less than or equal to `32`, since the function signature has `bytes32`.

Am I providing the wrong input? Am I required to encode the hex string into another format that will be accepted in `TypeEncoder.encode_raw`? I couldn't find a relevant example in the docs.

**Comment by roynalnaruto** [comment]
```elixir
"63cb2f697029ee491b58939796e9013087104b816ce0f51e731e9b03cc50c3b9"
|> String.upcase()
|> Base.encode16!()
```

can be used as the argument

**Comment by hswick** [comment]
@roynalnaruto there is a bytes_to_string method https://github.com/hswick/exw3/blob/master/lib/exw3.ex#L74, but it looks like you need the inverse.

I would merge a PR for this feature if you feel its worth your time.

**Comment by roynalnaruto** [comment]
> @roynalnaruto there is a bytes_to_string method https://github.com/hswick/exw3/blob/master/lib/exw3.ex#L74, but it looks like you need the inverse.
> 
> I would merge a PR for this feature if you feel its worth your time.

@hswick sure, I will create a PR
